Use local eslint instead of global, modify emojis

diff --git a/bin/pomander b/bin/pomander
--- a/bin/pomander
+++ b/bin/pomander
@@ -22,26 +22,26 @@ if [[ "$STAGED_FILES" = "" ]]; then
   exit 0
 fi
 
-# Check for ESLint
-which eslint &> /dev/null
-if [[ "$?" == 1 ]]; then
-  echo -e "${COLOR_RED}Pomander failed:${COLOR_RESET} ESLint not found! Please install ESLint"
-  echo -e "Make sure you have Node installed then run:"
-  echo -e "    ${COLOR_YELLOW}npm install -g eslint${COLOR_RESET}"
-  exit 1
-fi
+# Check for ESLint - nah
+# which eslint &> /dev/null
+# if [[ "$?" == 1 ]]; then
+#   echo -e "${COLOR_RED}Pomander failed:${COLOR_RESET} ESLint not found! Please install ESLint"
+#   echo -e "Make sure you have Node installed then run:"
+#   echo -e "    ${COLOR_YELLOW}npm install -g eslint${COLOR_RESET}"
+#   exit 1
+# fi
 
 # Lint files
 echo -e "${COLOR_MAGENTA}Sniffing your code, hang tight...${COLOR_RESET}"
 
 for FILE in $STAGED_FILES
 do
-  eslint "$FILE"
+  ./node_modules/.bin/eslint "$FILE"
 
   if [[ "$?" == 0 ]]; then
-    echo -e "👍  Passed: $FILE"
+    echo -e "💜  Passed: $FILE"
   else
-    echo -e "❌  Failed: $FILE"
+    echo -e "🙅  Failed: $FILE"
     PASSED=false
   fi
 done
